// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "CameraIntrinsicsCalc",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "CameraIntrinsicsCalc",
            targets: ["AppModule"],
            bundleIdentifier: "com.krithikrao.CameraIntrinsicsCalc",
            teamIdentifier: "A2QKBT4SNY",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cat),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Detm"),
                .photoLibraryAdd(purposeString: "Saving AR Photo to Library/")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)